spring:
  application:
    name: nine-forum-project
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: ${MYSQL_PASSWORD}
    url: jdbc:mysql://localhost:16033/nine_forum
  data:
    redis:
      port: 16379
      database: 0
  cache:
    redis:
      time-to-live: 86400
    cache-names: cache1
  security:
    jwt:
      secret-key: kenkouniyokunai
      expire: 7
  minio:
    endpoint: http://localhost:9000
    access-key: admin
    secret-key: qwert123
    bucket: nineforum
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    virtual-host: /nine_forum
    listener:
      simple:
        acknowledge-mode: manual
  mail:
    host: smtp.163.com
    username: ayor1337@163.com
    password: WEWshPE62xYFUTxr
  elasticsearch:
    uris: http://localhost:9200

server:
  port: 9966

#logging:
#  level:
#    org.springframework.messaging.simp: debug
#    org.springframework.messaging.simp.user: trace
#    org.springframework.web.socket.messaging: debug
#    org.springframework.messaging.simp.broker: debug

